### ISSUE TITLE
More rewards after votes

### ISSUE THREAD

**Issue by doducquang** [LDX-MCPE/VoteReward#10]
Ex:
1 vote - 1 A item 
2 votes - 2 A items 
3 votes - 1 B items 
4 votes - 2 B items + 1 A item

**Comment by LDX-MCPE** [comment]
This woild have to be implemented by server lists as well, but it could work...

**Comment by LDX-MCPE** [comment]
You have modified this suggestion. My previous response might not be valid.

**Comment by LDX-MCPE** [comment]
I'm sorry, but this idea is not plausible.
