### ISSUE TITLE
It Doesnt apply commands

### ISSUE THREAD

**Issue by CraftingMania** [LDX-MCPE/VoteReward#19]
it give the player things but only the portal command apply gut givemoney command and all others dont apply it was working like a charm on the old version please fix it

**Comment by LDX-MCPE** [comment]
Can you please post your config file here? You can remove any sensitive information if need be.

**Comment by CraftingMania** [comment]
first command wrok but i cant add more slots here it is

**Comment by CraftingMania** [comment]
# Config file for VoteReward by LDX.
#
# Official VoteReward Server List Directory:
# http://votereward.mcpe.me/?p=lists
#
# Config Variables:
#   {USERNAME} ... The username of the player who voted. ....... Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ... Commands and message.
#   {X} .......... The X coordinate of the player. ............. Commands only.
#   {Y} .......... The Y coordinate of the player. ............. Commands only.
#   {Y1} ......... The Y coordinate of the player plus 1. ...... Commands only.
#   {Z} .......... The Z coordinate of the player. ............. Commands only.

# EssentialsPE style color codes can be used in the message and commands.

# Message to broadcast to the server when a player votes.
Message: "The player &e{NICKNAME}&r voted with &b/vote&r and got cool rewards!"

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:
  - "264:0:20"
  - "265:0:15"
  - "266:0:15"

# List of commands to execute when a player votes.
Commands:
  - "particle portal {X} {Y1} {Z} 2 2 2 10000"
  - "givemoney {PLAYER} 8000"
  - "effect {PLAYER} Speed 1000"
  - "effect {PLAYER} Jump 1000"
  - "effect {PLAYER} Strength 1000"
  - "enchant {PLAYER} 9"
  - "xp 500 {PLAYER}"

**Comment by CraftingMania** [comment]
i removed the # because github make it bold

**Comment by CraftingMania** [comment]
but it exist and my config

**Comment by MinecraftList** [comment]
Try replacing {PLAYER} with {USERNAME}

**Comment by LDX-MCPE** [comment]
As @MinecraftList said, that is the issue. (PLAYER) was replaced with (USERNAME) in 3.0. I'll add backwards compatibility in 3.1.

**Comment by CraftingMania** [comment]
thx ldx your the best

**Comment by xDarkSaintx** [comment]
How To Put Creative Rewards?

**Comment by MiroTheSuperDev** [comment]
you cant creative reward

**Comment by xDarkSaintx** [comment]
Why other server have Creative Reward When voting ? Cuz I want make Creative Server
