### ISSUE TITLE
Loading problem { Crash dump }

### ISSUE THREAD

**Issue by Jorti1** [LDX-MCPE/VoteReward#23]
Very great plugins before it stated to make Crash dumps
After the 3.0 update it started to crash , so I when to the pocketmine fourms to download the  2.1 version , I moved to the plugins folder . It made a crash dump , after I unstalled it , my server stopped crashing .The crashed dump stated after vote rewards loaded 
If you want to view the crash dump see it here :

https://drive.google.com/file/d/0B4g0dcK1N_dyd21aRDBfTUctLXc/view?usp=docslist_api

**Comment by SleepSpace9** [comment]
Check your config.yml, the crash dump says that there is missing a quote at line 22.

**Comment by Jorti1** [comment]
The , this now works but after installing simple warp it has stopped working :(
