### ISSUE TITLE
If a player votes twice in a row very quickly; they get double rewards.

### ISSUE THREAD

**Issue by BlindTail** [LDX-MCPE/VoteReward#9]
If a player is able to /vote twice in a row very quickly; they will get double rewards. I'm not sure if this only happens when server is heavily loaded; or if it can be reproduced when under light load. 

Maybe this could be fixed by some kind of timer to not let them vote within the same minute?

**Comment by LDX-MCPE** [comment]
This is already being addressed in the latest update. Thank you for your bug report.

**Comment by LDX-MCPE** [comment]
This issue is no longer a bug because of its nonexistence in the upcoming complete rewrite.
